### PR TITLE
Algebraic statistics roser

### PR DESCRIPTION
**Pull request by roserhp**
Before merging it to the main branch, I would like you to take a look at the following in GraphicalModelsMLE:

- The reorganization of input data
- The documentation of sampleCovarianceMatrix and scoreEquations

### CODE REVIEW

**Comment by olgakuznetsova** [comment]
1. I wouldn’t add isPD, isPSD but instead allow checkPD, checkPSD accept a Matrix and just convert a Matrix to a List with one Matrix
2. https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L142 https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L215 probably better to perform this check somewhere here https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L260-L266 if not opts.sampleData because a covariance matrix can be non-symmetric only if the user introduces sth funny
3. LOVE the new Matrix set-up for sampleCovarianceMatrix
4. Having reread the documentation, I find the term “observations vector/data vector” to be quite confusing and also google doesn’t seem to give a unique definition either. Perhaps say how we index rows _and columns_ instead? https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L697 https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L776
5. “This is slightly different” -> “This is different” https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L701
6. “Maximisation” —> “Taking partial derivatives of” https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L772
7. https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L782 this is confusing because score equations are just the partials of the log-likelihood functions. This will not saturate the ideal of the score equations by the denominators of the partials
8. I would keep both lines https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L1171-L1172 Graph is a specific Type, so just leaving it the first line will be confusing
9. https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L1177-L1180 no, the output is a Sequence because we give several different items. I checked similar situations in M2
10. “Any kind of graph” is confusing https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L1183 perhaps, instead say “the same types of graphs at @TO gaussianRing@“
11. https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L1186 and the “maximum likelihood _estimators_” of the covariance matrix
12. Conflict between https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L349 and  https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L1186 In the code, the default is still the concentration matrix
13. What do you think if in  https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L349 we re-arrange the order of the optional arguments, so sampleData and concentrationMatrix come first as those are the ones people will most likely care about
14. Make this example with Matrix as input? https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L1192-L1195
15. “Below We compute”-> “Below we compute” https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L1188
16. “mixed graph”-> “MixedGraph” https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L1205
17. Missing SeeAlso in solverMLE, checkPD, checkPSD,scoreEquations, jacobianMatrix, sampleCovarianceMatrix

**Comment by roserhp** [comment]
Thanks for all the comments Olga!

1. That was my first idea, but I wanted to have a true or false output... But if we don't need to check if the sampleCovarianceMatrix is PD or PSD probably this is not necessary anymore and I can do what you said.

Now I'll go slowly through the rest.

**Comment by roserhp** [comment]
I will close this pull request and do a new one with all the changes.

I've done everything except for 1 (I'll do it but I need a bit more time) and 14 (because I think it's a good idea to have an example of list input).

**Comment by olgakuznetsova** [comment]
Re 14, I just commented that because our default input is a Matrix, so
would be logical if the first example actually uses a Matrix. Perhaps, we
can change so that the first takes in a Matrix and then the second takes in
a List or just make a separate example with List.




ti 3. marrask. 2020 klo 13.19 roserhp (notifications@github.com) kirjoitti:

**Comment by roserhp** [comment]
Ok, I'll do this in the next version (at some point before the meeting today)

**Pull request closed without merging**
